name: Building API Gateway

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin) + Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Download dependencies (go offline)
        run: ./mvnw -B -ntp dependency:go-offline

      - name: Build JAR (skip tests)
        run: ./mvnw -B -ntp clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error
